### ISSUE TITLE
[FEATURE] Add suport for config file like .db.yaml

### ISSUE THREAD

**Issue by danvergara** [danvergara/dblab#34]
**Is your feature request related to a problem? Please describe.**
Many tools like this, provide support for config files to customize or automate some tasks.

**Describe the solution you'd like**
Now, there are two ways to run the cli: 

1. By specifying the main individual flags:

```sh
$ dblab --host localhost --user myuser --db users --pass password --ssl disable --port 5432 --driver postgres
```

2. By defining the url flags:

```sh
$ db --url postgres://user:password@host:port/database
```

What if we'd just run the single binary with no flags, but a .dblab.yaml file has to be present with the necessary parameters to execute the application.

Example:

```yaml
config:
   host: localhost
   user: myuser
   db: users
   pass: password
   port: 5432
   driver: postgres
```

**Describe alternatives you've considered**
Other alternative is add a new flag called `config` that receives the path to the config file:

```sh
$ dblab --config ~/path/to/config
```

**Additional context**
This was originally proposed by @pa-m
